using APPLICATION.Dto.EducationalQualityAssuranceProgramObjectiveToJobRole;
using DOMAIN.Model;

namespace APPLICATION.IService.ObeAndCqi;

public interface IEducationalQualityAssuranceProgramObjectiveToJobRoleService:IGenericService<EducationalQualityAssuranceProgramObjectiveToJobRole, GetEducationalQualityAssuranceProgramObjectiveToJobRoleDto>
{
}
