using APPLICATION.Dto.EducationalQualityAssuranceAssessmentType;
using DOMAIN.Model;

namespace APPLICATION.IService.ObeAndCqi;

public interface IEducationalQualityAssuranceAssessmentTypeService:IGenericService<EducationalQualityAssuranceAssessmentType, GetEducationalQualityAssuranceAssessmentTypeDto>
{
}
