using APPLICATION.Dto.EducationalQualityAssuranceEducationalGoal;
using DOMAIN.Model;

namespace APPLICATION.IService.ObeAndCqi;

public interface IEducationalQualityAssuranceEducationalGoalService:IGenericService<EducationalQualityAssuranceEducationalGoal, GetEducationalQualityAssuranceEducationalGoalDto>
{
}
