using APPLICATION.Dto.EducationalQualityAssuranceProgramObjective;
using DOMAIN.Model;

namespace APPLICATION.IService.ObeAndCqi;

public interface IEducationalQualityAssuranceProgramObjectiveService:IGenericService<EducationalQualityAssuranceProgramObjective, GetEducationalQualityAssuranceProgramObjectiveDto>
{
}
