using APPLICATION.Dto.SkillsFrameworkPerformaceExpectationToJobRole;
using DOMAIN.Model;

namespace APPLICATION.IService.ObeAndCqi;

public interface ISkillsFrameworkPerformaceExpectationToJobRoleService:IGenericService<SkillsFrameworkPerformaceExpectationToJobRole, GetSkillsFrameworkPerformaceExpectationToJobRoleDto>
{
}
