using APPLICATION.Dto.SkillsFrameworkJobRoleToProficiencyLevel;
using DOMAIN.Model;

namespace APPLICATION.IService.ObeAndCqi;

public interface ISkillsFrameworkJobRoleToProficiencyLevelService:IGenericService<SkillsFrameworkJobRoleToProficiencyLevel, GetSkillsFrameworkJobRoleToProficiencyLevelDto>
{
}
