using APPLICATION.Dto.EducationalQualityAssuranceProgramObjectiveToJobRole;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface IEducationalQualityAssuranceProgramObjectiveToJobRoleService:IGenericService<EducationalQualityAssuranceProgramObjectiveToJobRole, GetEducationalQualityAssuranceProgramObjectiveToJobRoleDto>
{
}
