using APPLICATION.Dto.EducationalQualityAssuranceAssessmentType;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface IEducationalQualityAssuranceAssessmentTypeService:IGenericService<EducationalQualityAssuranceAssessmentType, GetEducationalQualityAssuranceAssessmentTypeDto>
{
}
