using APPLICATION.Dto.EducationalQualityAssuranceProgramObjective;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface IEducationalQualityAssuranceProgramObjectiveService:IGenericService<EducationalQualityAssuranceProgramObjective, GetEducationalQualityAssuranceProgramObjectiveDto>
{
}
