using APPLICATION.Dto.EducationalQualityAssuranceLearningObjective;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface IEducationalQualityAssuranceLearningObjectiveService:IGenericService<EducationalQualityAssuranceLearningObjective, GetEducationalQualityAssuranceLearningObjectiveDto>
{
}
