using APPLICATION.Dto.EducationalQualityAssuranceCourseObjective;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface IEducationalQualityAssuranceCourseObjectiveService:IGenericService<EducationalQualityAssuranceCourseObjective, GetEducationalQualityAssuranceCourseObjectiveDto>
{
}
