using APPLICATION.Dto.GradeBookItemToEqaLearningObjectiveMapping;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface IGradeBookItemToEqaLearningObjectiveMappingService:IGenericService<GradeBookItemToEqaLearningObjectiveMapping, GetGradeBookItemToEqaLearningObjectiveMappingDto>
{
}
