using APPLICATION.Dto.SkillsFrameworkJobRoleToProficiencyLevel;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface ISkillsFrameworkJobRoleToProficiencyLevelService:IGenericService<SkillsFrameworkJobRoleToProficiencyLevel, GetSkillsFrameworkJobRoleToProficiencyLevelDto>
{
}
