using APPLICATION.Dto.SkillsFrameworkPerformanceExpectation;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface ISkillsFrameworkPerformanceExpectationService:IGenericService<SkillsFrameworkPerformanceExpectation, GetSkillsFrameworkPerformanceExpectationDto>
{
}
