using APPLICATION.Dto.SkillsFrameworkJobRoleToCriticalWorkFunction;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface ISkillsFrameworkJobRoleToCriticalWorkFunctionService:IGenericService<SkillsFrameworkJobRoleToCriticalWorkFunction, GetSkillsFrameworkJobRoleToCriticalWorkFunctionDto>
{
}
