using APPLICATION.Dto.SkillsFrameworkCriticalWorkFunction;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface ISkillsFrameworkCriticalWorkFunctionService:IGenericService<SkillsFrameworkCriticalWorkFunction, GetSkillsFrameworkCriticalWorkFunctionDto>
{
}
