using APPLICATION.Dto.SkillsFrameworkCourseToCompetency;
using DOMAIN.Model;

namespace APPLICATION.IService;
public interface ISkillsFrameworkCourseToCompetencyService:IGenericService<SkillsFrameworkCourseToCompetency, GetSkillsFrameworkCourseToCompetencyDto>
{
}
